[2025-02-25T21:43:30.503+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.run_mapreduce_job manual__2025-02-25T21:43:13.407595+00:00 [queued]>
[2025-02-25T21:43:30.519+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.run_mapreduce_job manual__2025-02-25T21:43:13.407595+00:00 [queued]>
[2025-02-25T21:43:30.520+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-25T21:43:30.560+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce_job> on 2025-02-25 21:43:13.407595+00:00
[2025-02-25T21:43:30.573+0000] {standard_task_runner.py:57} INFO - Started process 219 to run task
[2025-02-25T21:43:30.577+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coingecko_ingestion_dag', 'run_mapreduce_job', 'manual__2025-02-25T21:43:13.407595+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpghmy4_oc']
[2025-02-25T21:43:30.586+0000] {standard_task_runner.py:85} INFO - Job 204: Subtask run_mapreduce_job
[2025-02-25T21:43:30.677+0000] {task_command.py:415} INFO - Running <TaskInstance: coingecko_ingestion_dag.run_mapreduce_job manual__2025-02-25T21:43:13.407595+00:00 [running]> on host 361f5ec071c2
[2025-02-25T21:43:30.816+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-02-25T21:43:30.914+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='coingecko_ingestion_dag' AIRFLOW_CTX_TASK_ID='run_mapreduce_job' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T21:43:13.407595+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-25T21:43:13.407595+00:00'
[2025-02-25T21:43:30.921+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-25T21:43:30.924+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        docker exec -i namenode         hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar           -input /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=25/coingecko_raw.json           -output /user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=25           -mapper /scripts/mapper.py           -reducer /scripts/reducer.py           -file /scripts/mapper.py           -file /scripts/reducer.py\n        ']
[2025-02-25T21:43:30.954+0000] {subprocess.py:86} INFO - Output:
[2025-02-25T21:43:31.922+0000] {subprocess.py:93} INFO - 2025-02-25 21:43:31,921 WARN streaming.StreamJob: -file option is deprecated, please use generic option -files instead.
[2025-02-25T21:43:33.038+0000] {subprocess.py:93} INFO - packageJobJar: [/scripts/mapper.py, /scripts/reducer.py] [] /tmp/streamjob4210007546880723401.jar tmpDir=null
[2025-02-25T21:43:33.050+0000] {subprocess.py:93} INFO - Exception in thread "main" java.io.IOException: expanding mapper.py would create file outside of /.
[2025-02-25T21:43:33.051+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.RunJar.unJar(RunJar.java:199)
[2025-02-25T21:43:33.052+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.StreamJob.submitAndMonitorJob(StreamJob.java:1011)
[2025-02-25T21:43:33.053+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.StreamJob.run(StreamJob.java:135)
[2025-02-25T21:43:33.054+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
[2025-02-25T21:43:33.056+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
[2025-02-25T21:43:33.056+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.HadoopStreaming.main(HadoopStreaming.java:50)
[2025-02-25T21:43:33.061+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-02-25T21:43:33.065+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-02-25T21:43:33.066+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-02-25T21:43:33.067+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-02-25T21:43:33.068+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
[2025-02-25T21:43:33.068+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
[2025-02-25T21:43:33.491+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-02-25T21:43:33.523+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-25T21:43:33.534+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=coingecko_ingestion_dag, task_id=run_mapreduce_job, execution_date=20250225T214313, start_date=20250225T214330, end_date=20250225T214333
[2025-02-25T21:43:33.563+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 204 for task run_mapreduce_job (Bash command failed. The command returned a non-zero exit code 1.; 219)
[2025-02-25T21:43:33.587+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-25T21:43:33.635+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
