[2025-02-25T21:26:09.974+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.run_mapreduce_job manual__2025-02-25T21:25:58.160080+00:00 [queued]>
[2025-02-25T21:26:09.997+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.run_mapreduce_job manual__2025-02-25T21:25:58.160080+00:00 [queued]>
[2025-02-25T21:26:09.998+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-25T21:26:10.030+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce_job> on 2025-02-25 21:25:58.160080+00:00
[2025-02-25T21:26:10.038+0000] {standard_task_runner.py:57} INFO - Started process 1329 to run task
[2025-02-25T21:26:10.049+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coingecko_ingestion_dag', 'run_mapreduce_job', 'manual__2025-02-25T21:25:58.160080+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpzyfew3cm']
[2025-02-25T21:26:10.058+0000] {standard_task_runner.py:85} INFO - Job 199: Subtask run_mapreduce_job
[2025-02-25T21:26:10.188+0000] {task_command.py:415} INFO - Running <TaskInstance: coingecko_ingestion_dag.run_mapreduce_job manual__2025-02-25T21:25:58.160080+00:00 [running]> on host af9744bbb9eb
[2025-02-25T21:26:10.317+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-02-25T21:26:10.419+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='coingecko_ingestion_dag' AIRFLOW_CTX_TASK_ID='run_mapreduce_job' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T21:25:58.160080+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-25T21:25:58.160080+00:00'
[2025-02-25T21:26:10.425+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-25T21:26:10.428+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        docker exec -i namenode         hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar           -input /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=25/coingecko_raw.json           -output /user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=25           -mapper /scripts/mapper.py           -reducer /scripts/reducer.py           -file /scripts/mapper.py           -file /scripts/reducer.py\n        ']
[2025-02-25T21:26:10.451+0000] {subprocess.py:86} INFO - Output:
[2025-02-25T21:26:11.331+0000] {subprocess.py:93} INFO - 2025-02-25 21:26:11,328 WARN streaming.StreamJob: -file option is deprecated, please use generic option -files instead.
[2025-02-25T21:26:11.688+0000] {subprocess.py:93} INFO - File: file:/scripts/mapper.py does not exist.
[2025-02-25T21:26:11.691+0000] {subprocess.py:93} INFO - Try -help for more information
[2025-02-25T21:26:11.694+0000] {subprocess.py:93} INFO - Streaming Command Failed!
[2025-02-25T21:26:11.753+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-02-25T21:26:11.774+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-25T21:26:11.784+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=coingecko_ingestion_dag, task_id=run_mapreduce_job, execution_date=20250225T212558, start_date=20250225T212609, end_date=20250225T212611
[2025-02-25T21:26:11.810+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 199 for task run_mapreduce_job (Bash command failed. The command returned a non-zero exit code 1.; 1329)
[2025-02-25T21:26:11.842+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-25T21:26:11.885+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
