[2025-02-24T18:14:19.984+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-23T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-02-24T18:14:19.988+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
