[2025-02-27T20:34:44.913+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.run_mapreduce_job manual__2025-02-27T20:29:16.247377+00:00 [queued]>
[2025-02-27T20:34:44.926+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.run_mapreduce_job manual__2025-02-27T20:29:16.247377+00:00 [queued]>
[2025-02-27T20:34:44.927+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 4
[2025-02-27T20:34:44.943+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce_job> on 2025-02-27 20:29:16.247377+00:00
[2025-02-27T20:34:44.950+0000] {standard_task_runner.py:57} INFO - Started process 409 to run task
[2025-02-27T20:34:44.953+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coingecko_ingestion_dag', 'run_mapreduce_job', 'manual__2025-02-27T20:29:16.247377+00:00', '--job-id', '415', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpgybc01ey']
[2025-02-27T20:34:44.956+0000] {standard_task_runner.py:85} INFO - Job 415: Subtask run_mapreduce_job
[2025-02-27T20:34:45.020+0000] {task_command.py:415} INFO - Running <TaskInstance: coingecko_ingestion_dag.run_mapreduce_job manual__2025-02-27T20:29:16.247377+00:00 [running]> on host 268c3735a020
[2025-02-27T20:34:45.096+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-02-27T20:34:45.131+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='coingecko_ingestion_dag' AIRFLOW_CTX_TASK_ID='run_mapreduce_job' AIRFLOW_CTX_EXECUTION_DATE='2025-02-27T20:29:16.247377+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-27T20:29:16.247377+00:00'
[2025-02-27T20:34:45.133+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-27T20:34:45.134+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        # نفحصو إذا المجلد موجود ونمسحوه إذا كان موجود\n        OUTPUT_DIR="/user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=27"\n        docker exec -i namenode bash -c "hdfs dfs -test -d $OUTPUT_DIR && hdfs dfs -rm -r $OUTPUT_DIR || echo \'Directory does not exist, proceeding...\'"\n\n        # نشغلو MapReduce\n        docker exec -i namenode         hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar         -input /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=27/coingecko_raw.json         -output $OUTPUT_DIR         -mapper "python3 /tmp/mapper.py"         -reducer "python3 /tmp/reducer.py"\n\n        docker exec -i namenode hdfs dfs -test -e $OUTPUT_DIR/part-00000 || (echo "MapReduce failed to produce output" && exit 1)\n        ']
[2025-02-27T20:34:45.149+0000] {subprocess.py:86} INFO - Output:
[2025-02-27T20:34:48.575+0000] {subprocess.py:93} INFO - Deleted /user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=27
[2025-02-27T20:34:50.805+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:50,803 INFO impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties
[2025-02-27T20:34:50.881+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:50,880 INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-02-27T20:34:50.881+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:50,880 INFO impl.MetricsSystemImpl: JobTracker metrics system started
[2025-02-27T20:34:50.911+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:50,908 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
[2025-02-27T20:34:51.295+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,294 INFO mapred.FileInputFormat: Total input files to process : 1
[2025-02-27T20:34:51.340+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,340 INFO mapreduce.JobSubmitter: number of splits:1
[2025-02-27T20:34:51.433+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,432 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_local1112744568_0001
[2025-02-27T20:34:51.434+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,432 INFO mapreduce.JobSubmitter: Executing with tokens: []
[2025-02-27T20:34:51.625+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,621 INFO mapreduce.Job: The url to track the job: http://localhost:8080/
[2025-02-27T20:34:51.631+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,627 INFO mapreduce.Job: Running job: job_local1112744568_0001
[2025-02-27T20:34:51.633+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,627 INFO mapred.LocalJobRunner: OutputCommitter set in config null
[2025-02-27T20:34:51.636+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,629 INFO mapred.LocalJobRunner: OutputCommitter is org.apache.hadoop.mapred.FileOutputCommitter
[2025-02-27T20:34:51.646+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,644 INFO output.FileOutputCommitter: File Output Committer Algorithm version is 2
[2025-02-27T20:34:51.647+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,644 INFO output.FileOutputCommitter: FileOutputCommitter skip cleanup _temporary folders under output directory:false, ignore cleanup failures: false
[2025-02-27T20:34:51.706+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,703 INFO mapred.LocalJobRunner: Waiting for map tasks
[2025-02-27T20:34:51.708+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,708 INFO mapred.LocalJobRunner: Starting task: attempt_local1112744568_0001_m_000000_0
[2025-02-27T20:34:51.728+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,727 INFO output.FileOutputCommitter: File Output Committer Algorithm version is 2
[2025-02-27T20:34:51.729+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,727 INFO output.FileOutputCommitter: FileOutputCommitter skip cleanup _temporary folders under output directory:false, ignore cleanup failures: false
[2025-02-27T20:34:51.739+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,738 INFO mapred.Task:  Using ResourceCalculatorProcessTree : [ ]
[2025-02-27T20:34:51.748+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,747 INFO mapred.MapTask: Processing split: hdfs://namenode:9000/user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=27/coingecko_raw.json:0+84418
[2025-02-27T20:34:51.762+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,762 INFO mapred.MapTask: numReduceTasks: 1
[2025-02-27T20:34:51.802+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,801 INFO mapred.MapTask: (EQUATOR) 0 kvi 26214396(104857584)
[2025-02-27T20:34:51.803+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,801 INFO mapred.MapTask: mapreduce.task.io.sort.mb: 100
[2025-02-27T20:34:51.804+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,801 INFO mapred.MapTask: soft limit at 83886080
[2025-02-27T20:34:51.806+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,801 INFO mapred.MapTask: bufstart = 0; bufvoid = 104857600
[2025-02-27T20:34:51.806+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,801 INFO mapred.MapTask: kvstart = 26214396; length = 6553600
[2025-02-27T20:34:51.807+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,805 INFO mapred.MapTask: Map output collector class = org.apache.hadoop.mapred.MapTask$MapOutputBuffer
[2025-02-27T20:34:51.815+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,812 INFO streaming.PipeMapRed: PipeMapRed exec [python3, /tmp/mapper.py]
[2025-02-27T20:34:51.822+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,816 INFO Configuration.deprecation: mapred.work.output.dir is deprecated. Instead, use mapreduce.task.output.dir
[2025-02-27T20:34:51.824+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,817 INFO Configuration.deprecation: map.input.start is deprecated. Instead, use mapreduce.map.input.start
[2025-02-27T20:34:51.824+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,817 INFO Configuration.deprecation: mapred.task.is.map is deprecated. Instead, use mapreduce.task.ismap
[2025-02-27T20:34:51.826+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,817 INFO Configuration.deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
[2025-02-27T20:34:51.830+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,818 INFO Configuration.deprecation: mapred.tip.id is deprecated. Instead, use mapreduce.task.id
[2025-02-27T20:34:51.831+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,818 INFO Configuration.deprecation: mapred.local.dir is deprecated. Instead, use mapreduce.cluster.local.dir
[2025-02-27T20:34:51.832+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,818 INFO Configuration.deprecation: map.input.file is deprecated. Instead, use mapreduce.map.input.file
[2025-02-27T20:34:51.833+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,819 INFO Configuration.deprecation: mapred.skip.on is deprecated. Instead, use mapreduce.job.skiprecords
[2025-02-27T20:34:51.836+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,819 INFO Configuration.deprecation: map.input.length is deprecated. Instead, use mapreduce.map.input.length
[2025-02-27T20:34:51.838+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,819 INFO Configuration.deprecation: mapred.job.id is deprecated. Instead, use mapreduce.job.id
[2025-02-27T20:34:51.839+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,819 INFO Configuration.deprecation: user.name is deprecated. Instead, use mapreduce.job.user.name
[2025-02-27T20:34:51.840+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,820 INFO Configuration.deprecation: mapred.task.partition is deprecated. Instead, use mapreduce.task.partition
[2025-02-27T20:34:51.842+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,833 ERROR streaming.PipeMapRed: configuration exception
[2025-02-27T20:34:51.842+0000] {subprocess.py:93} INFO - java.io.IOException: Cannot run program "python3": error=2, No such file or directory
[2025-02-27T20:34:51.843+0000] {subprocess.py:93} INFO - 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[2025-02-27T20:34:51.843+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:209)
[2025-02-27T20:34:51.843+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)
[2025-02-27T20:34:51.844+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-02-27T20:34:51.844+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-02-27T20:34:51.845+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-02-27T20:34:51.845+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-02-27T20:34:51.846+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:110)
[2025-02-27T20:34:51.846+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:79)
[2025-02-27T20:34:51.847+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:137)
[2025-02-27T20:34:51.847+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)
[2025-02-27T20:34:51.847+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-02-27T20:34:51.848+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-02-27T20:34:51.848+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-02-27T20:34:51.848+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-02-27T20:34:51.849+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:110)
[2025-02-27T20:34:51.849+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:79)
[2025-02-27T20:34:51.849+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:137)
[2025-02-27T20:34:51.849+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:462)
[2025-02-27T20:34:51.850+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:349)
[2025-02-27T20:34:51.850+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:271)
[2025-02-27T20:34:51.850+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2025-02-27T20:34:51.850+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2025-02-27T20:34:51.850+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-02-27T20:34:51.850+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-02-27T20:34:51.851+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:748)
[2025-02-27T20:34:51.851+0000] {subprocess.py:93} INFO - Caused by: java.io.IOException: error=2, No such file or directory
[2025-02-27T20:34:51.851+0000] {subprocess.py:93} INFO - 	at java.lang.UNIXProcess.forkAndExec(Native Method)
[2025-02-27T20:34:51.851+0000] {subprocess.py:93} INFO - 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
[2025-02-27T20:34:51.851+0000] {subprocess.py:93} INFO - 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
[2025-02-27T20:34:51.851+0000] {subprocess.py:93} INFO - 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[2025-02-27T20:34:51.852+0000] {subprocess.py:93} INFO - 	... 25 more
[2025-02-27T20:34:51.852+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,836 INFO mapred.LocalJobRunner: map task executor complete.
[2025-02-27T20:34:51.880+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:51,878 WARN mapred.LocalJobRunner: job_local1112744568_0001
[2025-02-27T20:34:51.880+0000] {subprocess.py:93} INFO - java.lang.Exception: java.lang.RuntimeException: Error in configuring object
[2025-02-27T20:34:51.880+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:492)
[2025-02-27T20:34:51.881+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:552)
[2025-02-27T20:34:51.881+0000] {subprocess.py:93} INFO - Caused by: java.lang.RuntimeException: Error in configuring object
[2025-02-27T20:34:51.881+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:113)
[2025-02-27T20:34:51.881+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:79)
[2025-02-27T20:34:51.881+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:137)
[2025-02-27T20:34:51.882+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:462)
[2025-02-27T20:34:51.882+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:349)
[2025-02-27T20:34:51.882+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:271)
[2025-02-27T20:34:51.882+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2025-02-27T20:34:51.882+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2025-02-27T20:34:51.883+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-02-27T20:34:51.883+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-02-27T20:34:51.883+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:748)
[2025-02-27T20:34:51.883+0000] {subprocess.py:93} INFO - Caused by: java.lang.reflect.InvocationTargetException
[2025-02-27T20:34:51.884+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-02-27T20:34:51.884+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-02-27T20:34:51.884+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-02-27T20:34:51.884+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-02-27T20:34:51.885+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:110)
[2025-02-27T20:34:51.885+0000] {subprocess.py:93} INFO - 	... 10 more
[2025-02-27T20:34:51.885+0000] {subprocess.py:93} INFO - Caused by: java.lang.RuntimeException: Error in configuring object
[2025-02-27T20:34:51.886+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:113)
[2025-02-27T20:34:51.886+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:79)
[2025-02-27T20:34:51.887+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:137)
[2025-02-27T20:34:51.887+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)
[2025-02-27T20:34:51.887+0000] {subprocess.py:93} INFO - 	... 15 more
[2025-02-27T20:34:51.887+0000] {subprocess.py:93} INFO - Caused by: java.lang.reflect.InvocationTargetException
[2025-02-27T20:34:51.888+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-02-27T20:34:51.888+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-02-27T20:34:51.888+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-02-27T20:34:51.888+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-02-27T20:34:51.888+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:110)
[2025-02-27T20:34:51.889+0000] {subprocess.py:93} INFO - 	... 18 more
[2025-02-27T20:34:51.889+0000] {subprocess.py:93} INFO - Caused by: java.lang.RuntimeException: configuration exception
[2025-02-27T20:34:51.889+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:222)
[2025-02-27T20:34:51.889+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)
[2025-02-27T20:34:51.890+0000] {subprocess.py:93} INFO - 	... 23 more
[2025-02-27T20:34:51.890+0000] {subprocess.py:93} INFO - Caused by: java.io.IOException: Cannot run program "python3": error=2, No such file or directory
[2025-02-27T20:34:51.890+0000] {subprocess.py:93} INFO - 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[2025-02-27T20:34:51.890+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:209)
[2025-02-27T20:34:51.891+0000] {subprocess.py:93} INFO - 	... 24 more
[2025-02-27T20:34:51.891+0000] {subprocess.py:93} INFO - Caused by: java.io.IOException: error=2, No such file or directory
[2025-02-27T20:34:51.891+0000] {subprocess.py:93} INFO - 	at java.lang.UNIXProcess.forkAndExec(Native Method)
[2025-02-27T20:34:51.891+0000] {subprocess.py:93} INFO - 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
[2025-02-27T20:34:51.892+0000] {subprocess.py:93} INFO - 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
[2025-02-27T20:34:51.892+0000] {subprocess.py:93} INFO - 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[2025-02-27T20:34:51.892+0000] {subprocess.py:93} INFO - 	... 25 more
[2025-02-27T20:34:52.640+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:52,639 INFO mapreduce.Job: Job job_local1112744568_0001 running in uber mode : false
[2025-02-27T20:34:52.641+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:52,640 INFO mapreduce.Job:  map 0% reduce 0%
[2025-02-27T20:34:52.643+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:52,643 INFO mapreduce.Job: Job job_local1112744568_0001 failed with state FAILED due to: NA
[2025-02-27T20:34:52.648+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:52,647 INFO mapreduce.Job: Counters: 0
[2025-02-27T20:34:52.648+0000] {subprocess.py:93} INFO - 2025-02-27 20:34:52,647 ERROR streaming.StreamJob: Job not successful!
[2025-02-27T20:34:52.649+0000] {subprocess.py:93} INFO - Streaming Command Failed!
[2025-02-27T20:34:54.977+0000] {subprocess.py:93} INFO - MapReduce failed to produce output
[2025-02-27T20:34:54.979+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-02-27T20:34:54.994+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-27T20:34:55.003+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=coingecko_ingestion_dag, task_id=run_mapreduce_job, execution_date=20250227T202916, start_date=20250227T203444, end_date=20250227T203455
[2025-02-27T20:34:55.022+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 415 for task run_mapreduce_job (Bash command failed. The command returned a non-zero exit code 1.; 409)
[2025-02-27T20:34:55.038+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-27T20:34:55.062+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
